### ISSUE TITLE
Run tests in travis-ci

### ISSUE THREAD

**Issue by cirocosta** [cirocosta/asciinema-edit#3]
Hey,

It'd be good to have Travis hooked to the publishing pipeline so it becomes easier to visualize the status of the tests.

I guess we can go with something as minimal as the following:

```yaml
sudo: false

language: 'go'

go:
  - 'master'

script:
  - 'make test'

notifications:
  email: false
```

Eventually, we can also hook up `goreleaser` to publish to GitHub releases whenever we're running in master in a new tag.

thx!
